# This is a basic workflow to help you get started with Actions

name: auto-assign

on:
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  add-reviews:
    runs-on: ubuntu-18.04
    steps: 
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2

      # 関係者の取得（ND CLIエクステンションを実行し、reviewer.yamlを生成する)
      - name: Make stakeholder list
        run: |
          echo -n -e 'addReviewers: true \naddAssignees: false \nreviewers: \n  - bleach31 \nnumberOfReviewers: 0 \n' > reviewers.yml
          cat reviewers.yml
          ls -la

      - name: check another step
        run: pwd 

      # レビュアーの割り当て
      # https://github.com/marketplace/actions/auto-assign-action
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: "reviewers.yml" 

